/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 githublogo.glb --transform 
Files: githublogo.glb [20.01KB] > Z:\art\models\githublogo\githublogo-transformed.glb [2.41KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function GithubLogo({position}) {
  const mesh = React.useRef()
  const [hovered, setHovered] = React.useState(false)
  const { nodes } = useGLTF('/models/githublogo-transformed.glb')

  useFrame(() => {
    mesh.current.rotation.y += 0.015
  })

  return (
    <group dispose={null} position={position} scale={0.75} ref={mesh}
      onPointerOver={(event) => setHovered(true)}
      onPointerOut={(event) => setHovered(false)}
      onClick={()=>window.open("https://github.com/j-xsen", "_blank")}>
      <mesh geometry={nodes.GithubLogo.geometry}>
        <meshBasicMaterial color={hovered ? [.5,.5,.5] : [1,1,1]} />
      </mesh>
      <mesh>
        <boxGeometry args={[5,5,1]}/>
        <meshBasicMaterial visible={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/githublogo-transformed.glb')
